integrations:
  kubernetes:
    name: kubernetes
    enabled: true
    namespace: default
    host: https://kubernetes.default.svc
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    insecure_skip_verify: true

prometheus:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s

server:
  http_listen_port: 12345

remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basicAuth:
      username: 1414101
      password: glc_eyJvIjoiODIyMDkyIiwibiI6InN0YWNrLTg1MTUwNC1obS13cml0ZS1ncmFmYW5hc3RhY2siLCJrIjoiNjgybFplTTdld1o3NjhWRVUxZ283NmZaIiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0=
